Name: Jim Patient
Patience: 1000
Intro: I've been on hold for 30 minutes, so happy that I've finally got someone one the phone!
80%: Can you speak more slowly? I'm not sure I follow.
60%: Are you sure you know what you're doing? I'm not sure this is right.
40%: Mfh, we already tried this, TWICE!
20%: Ahhhh, why is this so hard? Why are you so bad at your job?
0%: I can't beleive I wasted all my time on this! You're useless, GOOD DAY SIR.
Success: Oh wow! That actually worked! Thank you!
