name: Jim Patient
patience: 1000
intro: I've been on hold for 30 minutes, so happy that I've finally got someone one the phone!
win: Oh wow! That actually worked! Thank you!
lost: I can't beleive I wasted all my time on this! You're useless, GOOD DAY SIR.
-----
1 Can you speak more slowly? I'm not sure I follow.
1 Are you sure you know what you're doing? I'm not sure this is right.
2 Mfh, we already tried this, TWICE!
3 Ahhhh, why is this so hard? Why are you so bad at your job?
